version: '3.8'

services:
  arca-bot:
    build: .
    container_name: arca-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - LOG_LEVEL=${LOG_LEVEL}
      - VOICE_DEBUG=${VOICE_DEBUG}
      - WEBHOOK_LOGS_URL=${WEBHOOK_LOGS_URL}
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
